---
title: "Intervention Planning Systematic Review"
author: "Gerjo Kok, Louk Peters, Rik Crutzen & Gjalt-Jorn Peters"
date: "`r format(Sys.time(), '%H:%M:%S on %Y-%m-%d %Z (GMT%z)')`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
########################################################################
### Load packages
########################################################################

if (!require('ufs')) {              ### For convenience functions, e.g. 'checkPkgs'
  stop("You need the 'ufs' package installed!");
}
ufs::checkPkgs('here');             ### To easily access files using 'relative paths'
ufs::checkPkgs('plyr');             ### For easily processing and restructuring data
ufs::checkPkgs('dplyr');            ### Also for easily processing and restructuring data
ufs::checkPkgs('purrr');            ### Iteration and the %||% operator
ufs::checkPkgs('lubridate');        ### For working with dates
ufs::checkPkgs("googlesheets");     ### To import data from google sheets in metabefor
ufs::checkPkgs('jsonlite');         ### To import a list of country codes in metabefor
ufs::checkPkgs('knitr');            ### For kable
ufs::checkPkgs('ufs');              ### 
ufs::checkPkgs('data.tree');        ### To work with data structured in a tree in metabefor
ufs::checkPkgs('devtools');         ### To install packages from git repos
                                    ### ... Which we then do here:
#devtools::install_gitlab("r-packages/metabefor");
### Get old metabefor version
devtools::install_github("Matherion/metabefor");
require('metabefor');
devtools::install_github("academy-of-behavior-change/dct");
require('dct');

########################################################################
### Settings
########################################################################

### By default hide R code
knitr::opts_chunk$set(echo = FALSE);
knitr::opts_chunk$set(comment = NA);

### Set base path
basePath <- here::here();

### Set path for query hit exports
queryHitExportPath <- here::here("queries");

### Set path for screening
screeningPath <- here::here("screening");

### Set path for checklist
checklistPath <- here::here("checklist");

### Set path for any preliminary studies/work
prePath <- here::here("pre");

### Set path for extraction script template
extractionScriptTemplatePath <- here::here("extraction");

### Set path for intermediate output
outputPath <- here::here("output");

### Create object to keep track of queries
queries <- list();

### Simple function to correctly capture figures
figCap <- function(caption) {
  figCapCounter <-
    ifelse(is.null(getOption('figCapCounter')),
           0,
           getOption('figCapCounter'));
  figCapCounter <- figCapCounter + 1;
  options(figCapCounter = figCapCounter);
  return(paste0("Figure ", figCapCounter, ": ", caption));
}

### Set figure counter to 0
options(figCapCounter = 0);

```



```{r extraction-script-generation}

### Migrate the spreadsheet to the metabefor rxs

definitionsSheet <- 'Definitions';
localdefinitionsSheetFile <- file.path(basePath, 'wim-definitionsSheet.csv');

sheetsURL <- paste0("https://docs.google.com/spreadsheets/d/",
                    "1ByCHCThVha-EXRzTyQYoTTYv9e4N0Lj6btLBS6xrDHs");

valueTemplatesSheet <- "valueTemplates";
entitiesSheet <- "entities";

###----------------------------------------------------------------------------
###----------------------------------------------------------------------------
### Remove these commands once metabefor is cleaned up
###----------------------------------------------------------------------------
###----------------------------------------------------------------------------
require('userfriendlyscience');
require('data.tree');
require('dplyr');

options(metabefor.debug = TRUE);

fullObject <-
  metabefor:::rxs_fromSpecifications(gs_url = sheetsURL,
                                     entitiesFilename = file.path(extractionScriptTemplatePath,
                                                                  "entities-local-copy.csv"),
                                     valueTemplatesFilename = file.path(extractionScriptTemplatePath,
                                                                        "valueTemplates-local-copy.csv"),
                                     localBackup = list(entities = file.path(extractionScriptTemplatePath,
                                                                             "entities-local-copy.csv"),
                                                        valueTemplates= file.path(extractionScriptTemplatePath,
                                                                                  "valueTemplates-local-copy.csv"),
                                                        definitions = NULL),
                                     outputFile = file.path(extractionScriptTemplatePath,
                                                            "extractionScriptTemplate.rxs.Rmd"),
                                     returnFullObject = TRUE);

prepForDiagrammeR <- function(x) {
  return(gsub("[\"']",
              "`",
              paste(strwrap(x,
                            width=80),
                    collapse="\n")));
};

rxsTree_to_graph <- function(x) {
  newTree <-
    data.tree::Clone(x$rxsStructure$parsedEntities$extractionScriptTree);
  
  for (eachNode in x$rxsStructure$parsedEntities$recursingNodes) {
    newTree$AddChildNode(eachNode);
  }
  
  SetNodeStyle(newTree, label = function(x) {
    paste0(ifelse(is.null(x$title) || is.na(x$title),
                  "-",
                  prepForDiagrammeR(x$title)),
           "\n\n",
           ifelse(is.null(x$description) || is.na(x$description),
                  "-",
                  prepForDiagrammeR(x$description)),
           "\n\n",
           x$name);
  });

  diagTree <- data.tree::ToDiagrammeRGraph(newTree);

  diagTree <-
    dct::apply_graph_theme(diagTree,
                           c("layout", "dot", "graph"),
                           c("rankdir", "LR", "graph"),
                           c("outputorder", "nodesfirst", "graph"),
                           c("fixedsize", "false", "node"),
                           c("shape", "box", "node"),
                           c("style", "rounded,filled", "node"),
                           c("color", "#000000", "node"),
                           c("margin", "0.8,0.1", "node"),
                           c("fontname", "Nobile", "node"),
                           c("color", "#888888", "edge"),
                           c("dir", "forward", "edge"),
                           c("fillcolor", "#FFFFFF", "node"));

  invisible(return(diagTree));
}

plot.rxsStructure <- function(x, ...) {
  diagTree <- rxsTree_to_graph(x);
  return(DiagrammeR::render_graph(diagTree));
}

#plot(fullObject);

export.rxsStructure <- function(x,
                                filename,
                                ext='svg',
                                ...) {

  diagTree <- rxsTree_to_graph(x);

  invisible(DiagrammeR::export_graph(graph=diagTree,
                                     file_name=filename,
                                     file_type=ext));
}

export.rxsStructure(fullObject,
                    filename=file.path(outputPath,
                                       "full-extractionscript-tree.svg"),
                    ext='svg');

export.rxsStructure(fullObject,
                    filename=file.path(outputPath,
                                       "full-extractionscript-tree.pdf"),
                    ext='pdf');

```

#### Extraction script template

```{r extraction-script-template, results="asis"}
cat("\n\n<pre><textarea rows='40' cols='124' style='font-family:monospace;font-size:11px;white-space:pre;'>",
    unlist(fullObject$rxsTemplate),
    "</textarea></pre>\n\n",
    sep="\n");
```

#### Checklist

```{r checklist-functions}

### http://stackoverflow.com/questions/3665115/create-a-file-in-memory-for-user-to-download-not-through-server

###############################################################################
###############################################################################
### Checklist functions
###############################################################################
###############################################################################

returnPathToRoot <- function(node, considerRoot = newRootName){#rootName) {
  res <- paste0(rev(unlist(sapply(Traverse(node, traversal='ancestor'),
                                  function(x) return(x$name)),
                           recursive=TRUE)), collapse="$");
  res <- gsub(paste0("^.*\\$", considerRoot, "$"), "", res);
  res <- gsub(paste0("^.*\\$", considerRoot, "\\$"), "\\$", res);
  return(res);
}

isCollapsing <- function(x) {
  if (is.null(x)) {
    return(FALSE);
  } else if (is.na(x)) {
    return(FALSE);
  } else if (nchar(x) == 0) {
    return(FALSE);
  } else if (trim(toupper(x)) == "OR") {
    return(TRUE);
  } else if (trim(toupper(x)) == "AND") {
    return(TRUE);
  } else {
    stop("For 'Collapsing', value '", x, "' encountered.");
  }
}

isRecursive <- function(x) {
  if (is.null(x)) {
    return(FALSE);
  } else if (is.na(x)) {
    return(FALSE);
  } else if (nchar(trim(x)) == 0) {
    return(FALSE);
  } else if (nchar(trim(x)) > 0) {
    return(TRUE);
  }
}

isRepeating <- function(x) {
  if (is.null(x)) {
    return(FALSE);
  } else if (is.na(x)) {
    return(FALSE);
  } else if (nchar(x) == 0) {
    return(FALSE);
  } else if (trim(toupper(x)) == "FALSE") {
    return(FALSE);
  } else if (trim(toupper(x)) == "TRUE") {
    return(TRUE);
  } else {
    stop("For 'Repeating', value '", x, "' encountered.");
  }
}

hasOwner <- function(x) {
  if (is.null(x)) {
    return(FALSE);
  } else if (is.na(x)) {
    return(FALSE);
  } else if (nchar(trim(x)) == 0) {
    return(FALSE);
  } else if (nchar(trim(x)) > 0) {
    return(TRUE);
  }
}


generateChecklistElements <- function(node) {

  lvl <- node$level;
  id <- node$name;
  if (isRecursive(node[[recursionColName]]) && !isTrue(node[[recursionColName]])) {
      if (node$trulyRecursive) {
        return("<div>Another truly recursive element</div>");
      }
      ### Insert the recursive element here
    return(paste0('<div class="metabefor-nesting metabefor-nesting-level', lvl, '">\n',
                  '<h', lvl, '>', node$ChecklistTitle, '</h', lvl, '>\n',
                  "<p class='metabefor-checkbox-description'>", node$ChecklistDescription, "</p>",
                  paste0(sapply(FindNode(extractionScriptTree, name=node[[recursionColName]])$children,
                           generateChecklistElements), collapse="\n"),
                  '</div>'));
  } else if (isLeaf(node)) {
    
    ### We're going to construct a checkbox, with a name (title) and a description,
    ### as well as three buttons to toggle the checkbox status.
    ### To prevent recursive elements to have duplicated id's, we need to add
    ### a unique string to the id.
    uniqueId <- paste0(c(node$name,
                         as.numeric(format(Sys.time(), "%OS3")) * 1000,
                         sample(LETTERS, 3, TRUE)),
                       collapse="");
    
    return(paste0("<div class='metabefor-checkbox-container'>",

                  #"<br><br>", node$name, "<br><br>",

                  "<div id='metabefor-checkbox-", uniqueId, "' class='metabefor-checkbox-svg-container'>",
                  
                  
                  '<svg xmlns="https://www.w3.org/2000/svg" version="1.1" viewBox="0 0 11.1125 11.112501" height="42" width="42"><path style="fill:#FFFFFF;fill-opacity:1;fill-rule:evenodd;stroke:none;" d="M 0.72039847,5.5008244 5.0912096,10.409253 10.343529,0.77453521 4.4461307,7.4949906 Z" class="checkbox-checkmark" /><path style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:0.5291667;stroke-linecap:square;stroke-linejoin:miter;stroke-miterlimit:4;stroke-dasharray:none;stroke-opacity:1;fill-opacity:1" d="M 0.26458335,0.26458335 H 10.847916 V 10.847916 H 0.26458335 v -10.58333265 0" class="checkbox-border" /></svg>',


                  "</div>",
                  
                  
                  "<div class='metabefor-buttons'>\n",
                  "<span class='metabefor-checklist-title'>\n",
                  node$checklistTitle,
                  "</span>",
                  "<span class='metabefor-checkbox-description'>",
                  node$checklistDescription,
                  "</span>\n",
                  
                  "<div class='metabefor-book-reference' id='#metabefor-bookreference-", node$name, "'>",
                  ifelse(grepl("[A-Za-z]", node$BookReference_4),
                         paste0("<p>", node$BookReference_4, "</p>"),
                         paste0("<p>More information in the Intervention Mapping book, fourth edition, at page ",
                                node$BookReference_4, " and further.</p>")),
                  ifelse(nchar(node$OtherReference) > 0,
                         paste0("<p>", node$OtherReference, "</p>"),
                         ""),
                  "</div>\n",
                  
                  
                  '<div class="btn-group metabefor-buttongroup" data-toggle="buttons" aria-label="Options">\n',
                  '<label class="btn btn-success" onclick="checkboxYes(\'', uniqueId, '\')">\n',
                  '<input type="radio" name="options" id="metabefor-checkbox-', uniqueId, '-yes" autocomplete="off"></input> Did this',
                  '</label>',
                  '<label class="btn btn-danger" onclick="checkboxNo(\'', uniqueId, '\')">\n',
                  '<input type="radio" name="options" id="metabefor-checkbox-', uniqueId, '-no" autocomplete="off"></input> Did not do this',
                  '</label>',
                  '<label class="btn btn-primary" onclick="checkboxNA(\'', uniqueId, '\')">\n',
                  '<input type="radio" name="options" id="metabefor-checkbox-', uniqueId, '-na" autocomplete="off"></input> Not applicable',
                  '</label>',

                  "</div>\n",
                  "\n</div>\n",
                  "</div>"));
  } else {
    return(paste0('<div class="metabefor-nesting metabefor-nesting-level', lvl, '">\n',
                  '<h', lvl, '>', node$ChecklistTitle, '</h', lvl, '>\n',
                  paste0(sapply(node$children, generateChecklistElements), collapse="\n"),
                  '</div>'));
  }
}

renderChecklist <- function(extractionScriptTree,
                            checklistRoot = NULL,
                            preChecklistHtml = NULL,
                            outputFile = NULL,
                            css = "html {\n  font-family: sans-serif;\n}",
                            header = paste0('<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">\n',
                                            '<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>\n',
                                            '<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>\n'),
                            footer = "<script>\n$(document).ready(function(){\n  $('[data-toggle=\"tooltip\"]').tooltip();\n});\n</script>",
                            cssURL = NULL,
                            definitions = NULL,
                            definitionsTermsCol = 'term',
                            definitionsDefCol = 'definition') {

  checklistHeader <- "<html>\n\n<head>";
  checklistScript <- "";

  ### Add header info
  if (!is.null(header)) {
    if (file.exists(header)) {
      checklistHeader <- paste0(checklistHeader, '\n',
                                paste0(readLines(header), collapse="\n"),
                                '\n');
    } else {
      checklistHeader <- paste0(checklistHeader, header, '\n');
    }
  }
  
  ### Add stylesheet info
  if (!is.null(cssURL)) {
    checklistHeader <- paste0(checklistHeader, '<link rel="stylesheet" type="text/css" href="', cssURL, '">\n');
  } else if (file.exists(css)) {
    checklistHeader <- paste0(checklistHeader, '<style>\n',
                            paste0(readLines(css), collapse="\n"),
                            '</style>\n');
  } else {
    checklistHeader <- paste0(checklistHeader, "<style>\n", css, "\n</style>\n");
  }
    
  checklistHeader <- paste0(checklistHeader, "</head>\n\n<body>\n");
  
  if (is.null(checklistRoot)) {
    checklistRoot <- extractionScriptTree$root$name;
  }

  checklistBody <- paste0(sapply(FindNode(extractionScriptTree, checklistRoot)$children,
                                 generateChecklistElements),
                          collapse="\n");

  for (i in 1:nrow(definitions)) {
    ### Add tooltip to glossary terms - make sure that the regex SKIPs/FAIL
    ### when inside an A element (i.e. when already inside a tooltop).
    
    ### <a[^>]*>[^<]*<\\/a
    ### <input[^>]*>[^<]*<\\/input
    ### (*SKIP)(*FAIL)
    
    ### See http://www.rexegg.com/regex-best-trick.html
    
    #matchString <- paste0("(?:<a[^>]*>[^<]*<\\/a|<input[^>]*>[^<]*<\\/input|<div[^>]*>[^<]*<\\/div)(*SKIP)(*FAIL)|(", definitions[i, definitionsTermsCol], ")");
    
    ### From https://stackoverflow.com/questions/18621568/regex-replace-text-outside-html-tags (2018-04-12)
    #matchString <- paste0("(", definitions[i, definitionsTermsCol], ")(?![^<]*>|[^<>]*<\\/)");
    
    ### Only replace if it occurs within the description
    matchString <- paste0("(<span class='metabefor-checkbox-description'>[^<]*)(",
                          definitions[i, definitionsTermsCol],
                          ")([^<]*<\\/span>)");
    
    definitionToolTip <- paste0('\\1<a class="metabefor-term-definition" data-toggle="tooltip" title="',
                                definitions[i, definitionsDefCol],
    #                            '">', definitions[i, definitionsTermsCol], '</a>');
                                '">\\2</a>\\3');

  checklistBody <- gsub(matchString, definitionToolTip,
                        checklistBody, ignore.case = TRUE, perl=FALSE);

    ### From https://stackoverflow.com/questions/14621094/how-to-replace-the-text-inside-an-xml-element-in-r
    # docAsHTML <- htmlParse(file = checklistBody, asText = TRUE);
    # nodes <- getNodeSet(docAsHTML, "//Text");
    # lapply(nodes, function(n) {
    #   xmlValue(n) <- gsub(definitions[i, definitionsTermsCol],
    #                       "definitionToolTip",
    #                       xmlValue(n));
    # });
    # 
    # checklistBody <- saveXML(docAsHTML);
    # 
    ### https://github.com/PebbleRoad/glossarizer
    
  }

  ### Add footer info
  if (!is.null(footer)) {
    if (file.exists(footer)) {
      checklistFooter <- paste0(readLines(footer), collapse="\n");
    } else {
      checklistFooter <- footer;
    }
  }
  
  definitionTermsOrder <- order(pull(definitions, definitionsTermsCol));
  
  checklistDefinitions <- paste0("<div class='metabefor-definitions-container'>\n",
                                 "<div id='metabefor-definitions-toggle'>\n",
                                 "Glossary (click here to toggle definitions)</div>\n",
                                 "<div id='metabefor-definitions-overflowbox'>",
                                 "<table id='metabefor-definitions'>\n",
                                 paste0(paste0("<tr>\n",
                                               "<td class='metabefor-definitions-term-column'>",
                                               pull(definitions, definitionsTermsCol)[definitionTermsOrder],
                                               "</td>\n",
                                               "<td class='metabefor-definitions-definition-column'>",
                                               pull(definitions, definitionsDefCol)[definitionTermsOrder],
                                               "</td>\n",
                                               "</tr>\n"),
                                        collapse="\n"),
                                 "</table>\n</div>\n",
                                 "</div>\n");
  
  checklistScript <- paste0(checklistScript,
                            '\n$(document).ready(function(){\n',
                            "  var visible = false;",
                            '$( "#metabefor-definitions-toggle" ).click(function() {\n',
                            "  if ( visible ) {\n",
                            "    $( '#metabefor-definitions-overflowbox' ).slideUp('fast',function(){\n",
                            "      $( '#metabefor-definitions-overflowbox' ).addClass('metabefor-hidden')\n",
                            "           .slideDown(0);\n",
                            "    });\n",
                            "  } else {\n",
                            "    $( '#metabefor-definitions-overflowbox' ).slideUp(0,function(){\n",
                            "      $( '#metabefor-definitions-overflowbox' ).removeClass('metabefor-hidden')\n",
                            "           .slideDown('fast');\n",
                            "    });\n",
                            "  }\n",
                            "  visible = ! visible;\n",
                            "});\n",
                            '});');
  
  checklistScript <- paste0(checklistScript, "

  checkboxYes = function(elementIdentifier) {
    $('#metabefor-checkbox-'+elementIdentifier+' .checkbox-checkmark').css(\"fill\", \"#008800\");
    $('#metabefor-checkbox-'+elementIdentifier+' .checkbox-border').css(\"stroke\", \"#008800\");
    $('#metabefor-bookreference-'+elementIdentifier).hide();
  }
  
  checkboxNo = function(elementIdentifier) {
    $('#metabefor-checkbox-'+elementIdentifier+' .checkbox-checkmark').css(\"fill\", \"#FFFFFF\");
    $('#metabefor-checkbox-'+elementIdentifier+' .checkbox-border').css(\"stroke\", \"#880000\");
    $('#metabefor-bookreference-'+elementIdentifier).show();
  }

  checkboxNA = function(elementIdentifier) {
    $('#metabefor-checkbox-'+elementIdentifier+' .checkbox-checkmark').css(\"fill\", \"#FFFFFF\");
    $('#metabefor-checkbox-'+elementIdentifier+' .checkbox-border').css(\"stroke\", \"#CCCCDD\");
    $('#metabefor-bookreference-'+elementIdentifier).hide();
  }

  ");

  preChecklistHtmlText <- "";
  if (!is.null(preChecklistHtml)) {
    if (file.exists(preChecklistHtml)) {
      preChecklistHtmlText <- readLines(preChecklistHtml,
                                        encoding="UTF-8");
    }
  } 

  ### (The metabefor-header and the checklist definitions are placed after the main
  ###  content, so that it's rendered on top of that content.)
  checklistBody <- paste0(checklistHeader, "\n",
                          "\n<div class='metabefor-content-container'>\n",
                          paste(preChecklistHtmlText, collapse="\n", sep="\n"),
                          "\n<div class=\"form-group\">\n",
                          checklistBody, "\n",
                          "</div>\n</div>\n",
                          checklistFooter, "\n",
                          "\n<div class='metabefor-header'>",
                          checklistDefinitions,
                          "</div>\n",
                          "\n</body>\n<script>\n",
                          checklistScript,
                          "\n</script>\n</html>\n");
  
  ### Replace UTF-8 non-breaking spaces with regular spaces
  ### https://stackoverflow.com/questions/14720493/replace-a-utf-8-character-in-r
  checklistBody <- gsub('\U00A0', ' ', checklistBody);

  if (!is.null(outputFile)) {
    outputFileCon <- file(outputFile,
                          "w",
                          encoding="UTF-8");
    writeLines(paste0(checklistBody, collapse=""),
               con=outputFileCon);
    close(outputFileCon);
  }
  
  invisible(checklistBody);

}

```

```{r checklist-production}

########################################################################
### Settings (will become parameters/arguments)
########################################################################

newRootName <- 'res';
rootName <- 'intervention';
recursionsName <- 'recursion';
lvlIndentString <- "  ";
repeatingColName <- "repeating";
recursionColName <- "recursion";
collapsingColName <- "collapse";
ownerColName <- "owner";
parentColName <- "parent";
identifierColName <- "identifier";
activityColName <- "title";
descriptionColName <- "description";
definitionsTermsCol = 'term';
definitionsDefCol = 'definition';
valueName <- "value";
defaultValue <- "NA";
recursiveElementPlaceholderName <- "recursiveElementPlaceholder";
extractionSheet <- 'entities';
definitionsSheet <- 'definitions';

### Load checklist definitions
tryCatch({
  ufs::cat0("\nReading definitions sheet from Google Docs.\n");
  definitions <- googlesheets::gs_read(googlesheets::gs_url(sheetsURL), ws = definitionsSheet);
  ufs::cat0("\nStoring definitions sheet in local file.\n");
  write.csv(definitions, row.names=FALSE, localdefinitionsSheetFile);
}, error = function(e) {
  ufs::cat0("\nReading definitions sheet from local file.\n");
  definitions <<- read.csv(localdefinitionsSheetFile,
                           stringsAsFactors = FALSE);
});

renderChecklist(fullObject$rxsStructure$parsedEntities$extractionScriptTree,
                checklistRoot = 'intervention',
                preChecklistHtml = file.path(checklistPath, "checklist_frontpage.html"),
                outputFile = file.path(checklistPath, "checklist.html"),
                css = file.path(checklistPath, 'checklist.css'),
                definitions = definitions);

```
